language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction

script: vendor/bin/phpunit --configuration phpunit.xml

notifications:
  email: false
